# Site settings
name: Daniel M Hanover
email: hanover.daniel@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Parallel Entrepreneur and Software Developer"
skills: "Extremely fluent in both web and iOS technologies"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/danielmhanover/
  - title: medium
    url: https://medium.com/@danielmhanover
  - title: twitter
    url: https://twitter.com/danielmhanover
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 008edb
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
